# install Cask
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

# install cli binaries and tools
brew zsh
brew httpie
brew python3
brew node@12
brew vim

# install apps
cask "docker"
cask "firefox"
cask "google-chrome"
cask "postman"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "iterm2"
cask "alfred"

# Quick Look Plugins (https://github.com/sindresorhus/quick-look-plugins)
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "suspicious-package"
cask "webpquicklook"

# awesome fonts
cask "font-source-code-pro"

# install mac app store apps
mas "1Password", id: 443987910
